# Generated by Django 5.2 on 2025-04-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level_requirement', models.IntegerField(default=1)),
                ('level_reward', models.IntegerField(default=1)),
            ],
        ),
    ]
