# Generated by Django 5.2 on 2025-04-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='Default Name', max_length=100),
        ),
    ]
