# Generated by Django 5.2 on 2025-04-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_quiz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='language',
            field=models.CharField(default='jp', max_length=2),
        ),
    ]
