/*
 * Copyright (C) 2023 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.example.languagelearner.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF1F1515)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF352929)
val onPrimaryContainerLight = Color(0xFFA18F8F)
val secondaryLight = Color(0xFF645D5B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFF4F1)
val onSecondaryContainerLight = Color(0xFF766F6D)
val tertiaryLight = Color(0xFF775749)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD4C2)
val onTertiaryContainerLight = Color(0xFF7A5A4C)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFEF8F7)
val onBackgroundLight = Color(0xFF1D1B1B)
val surfaceLight = Color(0xFFFEF8F7)
val onSurfaceLight = Color(0xFF1D1B1B)
val surfaceVariantLight = Color(0xFFEEDFDE)
val onSurfaceVariantLight = Color(0xFF4E4444)
val outlineLight = Color(0xFF807474)
val outlineVariantLight = Color(0xFFD1C3C3)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF323030)
val inverseOnSurfaceLight = Color(0xFFF5EFEF)
val inversePrimaryLight = Color(0xFFD6C2C2)
val surfaceDimLight = Color(0xFFDED9D8)
val surfaceBrightLight = Color(0xFFFEF8F7)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF8F2F1)
val surfaceContainerLight = Color(0xFFF2EDEC)
val surfaceContainerHighLight = Color(0xFFEDE7E6)
val surfaceContainerHighestLight = Color(0xFFE7E1E0)

val primaryLightMediumContrast = Color(0xFF1F1515)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF352929)
val onPrimaryContainerLightMediumContrast = Color(0xFFC7B4B4)
val secondaryLightMediumContrast = Color(0xFF3B3533)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF736B69)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF4A3024)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF876657)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFEF8F7)
val onBackgroundLightMediumContrast = Color(0xFF1D1B1B)
val surfaceLightMediumContrast = Color(0xFFFEF8F7)
val onSurfaceLightMediumContrast = Color(0xFF121111)
val surfaceVariantLightMediumContrast = Color(0xFFEEDFDE)
val onSurfaceVariantLightMediumContrast = Color(0xFF3D3434)
val outlineLightMediumContrast = Color(0xFF5A5050)
val outlineVariantLightMediumContrast = Color(0xFF766A6A)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF323030)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF5EFEF)
val inversePrimaryLightMediumContrast = Color(0xFFD6C2C2)
val surfaceDimLightMediumContrast = Color(0xFFCAC5C5)
val surfaceBrightLightMediumContrast = Color(0xFFFEF8F7)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF8F2F1)
val surfaceContainerLightMediumContrast = Color(0xFFEDE7E6)
val surfaceContainerHighLightMediumContrast = Color(0xFFE1DCDB)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD6D0D0)

val primaryLightHighContrast = Color(0xFF1F1515)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF352929)
val onPrimaryContainerLightHighContrast = Color(0xFFF5E0E0)
val secondaryLightHighContrast = Color(0xFF302B29)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF4E4846)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF3F261A)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF604235)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFEF8F7)
val onBackgroundLightHighContrast = Color(0xFF1D1B1B)
val surfaceLightHighContrast = Color(0xFFFEF8F7)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFEEDFDE)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF332A2A)
val outlineVariantLightHighContrast = Color(0xFF514747)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF323030)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFD6C2C2)
val surfaceDimLightHighContrast = Color(0xFFBCB8B7)
val surfaceBrightLightHighContrast = Color(0xFFFEF8F7)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF5EFEF)
val surfaceContainerLightHighContrast = Color(0xFFE7E1E0)
val surfaceContainerHighLightHighContrast = Color(0xFFD9D3D2)
val surfaceContainerHighestLightHighContrast = Color(0xFFCAC5C5)

val primaryDark = Color(0xFFD6C2C2)
val onPrimaryDark = Color(0xFF3A2D2D)
val primaryContainerDark = Color(0xFF352929)
val onPrimaryContainerDark = Color(0xFFA18F8F)
val secondaryDark = Color(0xFFFFFFFF)
val onSecondaryDark = Color(0xFF352F2D)
val secondaryContainerDark = Color(0xFFEBE0DD)
val onSecondaryContainerDark = Color(0xFF6A6361)
val tertiaryDark = Color(0xFFFFF8F6)
val onTertiaryDark = Color(0xFF442A1E)
val tertiaryContainerDark = Color(0xFFFFD4C2)
val onTertiaryContainerDark = Color(0xFF7A5A4C)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF151313)
val onBackgroundDark = Color(0xFFE7E1E0)
val surfaceDark = Color(0xFF151313)
val onSurfaceDark = Color(0xFFE7E1E0)
val surfaceVariantDark = Color(0xFF4E4444)
val onSurfaceVariantDark = Color(0xFFD1C3C3)
val outlineDark = Color(0xFF9A8E8D)
val outlineVariantDark = Color(0xFF4E4444)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE7E1E0)
val inverseOnSurfaceDark = Color(0xFF323030)
val inversePrimaryDark = Color(0xFF6A5B5B)
val surfaceDimDark = Color(0xFF151313)
val surfaceBrightDark = Color(0xFF3B3938)
val surfaceContainerLowestDark = Color(0xFF0F0E0E)
val surfaceContainerLowDark = Color(0xFF1D1B1B)
val surfaceContainerDark = Color(0xFF211F1F)
val surfaceContainerHighDark = Color(0xFF2C2929)
val surfaceContainerHighestDark = Color(0xFF363434)

val primaryDarkMediumContrast = Color(0xFFECD8D7)
val onPrimaryDarkMediumContrast = Color(0xFF2E2323)
val primaryContainerDarkMediumContrast = Color(0xFF9E8D8C)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFFFFFFF)
val onSecondaryDarkMediumContrast = Color(0xFF352F2D)
val secondaryContainerDarkMediumContrast = Color(0xFFEBE0DD)
val onSecondaryContainerDarkMediumContrast = Color(0xFF4D4745)
val tertiaryDarkMediumContrast = Color(0xFFFFF8F6)
val onTertiaryDarkMediumContrast = Color(0xFF442A1E)
val tertiaryContainerDarkMediumContrast = Color(0xFFFFD4C2)
val onTertiaryContainerDarkMediumContrast = Color(0xFF5B3E31)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF151313)
val onBackgroundDarkMediumContrast = Color(0xFFE7E1E0)
val surfaceDarkMediumContrast = Color(0xFF151313)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF4E4444)
val onSurfaceVariantDarkMediumContrast = Color(0xFFE8D9D8)
val outlineDarkMediumContrast = Color(0xFFBCAFAE)
val outlineVariantDarkMediumContrast = Color(0xFF9A8D8D)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE7E1E0)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2C2929)
val inversePrimaryDarkMediumContrast = Color(0xFF524545)
val surfaceDimDarkMediumContrast = Color(0xFF151313)
val surfaceBrightDarkMediumContrast = Color(0xFF464444)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF080707)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1F1D1D)
val surfaceContainerDarkMediumContrast = Color(0xFF292727)
val surfaceContainerHighDarkMediumContrast = Color(0xFF343232)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3F3D3D)

val primaryDarkHighContrast = Color(0xFFFFECEB)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFD2BEBE)
val onPrimaryContainerDarkHighContrast = Color(0xFF120909)
val secondaryDarkHighContrast = Color(0xFFFFFFFF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFEBE0DD)
val onSecondaryContainerDarkHighContrast = Color(0xFF2E2927)
val tertiaryDarkHighContrast = Color(0xFFFFF8F6)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFFFFD4C2)
val onTertiaryContainerDarkHighContrast = Color(0xFF382015)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF151313)
val onBackgroundDarkHighContrast = Color(0xFFE7E1E0)
val surfaceDarkHighContrast = Color(0xFF151313)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF4E4444)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFFCECEC)
val outlineVariantDarkHighContrast = Color(0xFFCDBFBF)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE7E1E0)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF524545)
val surfaceDimDarkHighContrast = Color(0xFF151313)
val surfaceBrightDarkHighContrast = Color(0xFF524F4F)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF211F1F)
val surfaceContainerDarkHighContrast = Color(0xFF323030)
val surfaceContainerHighDarkHighContrast = Color(0xFF3D3B3B)
val surfaceContainerHighestDarkHighContrast = Color(0xFF494646)