# Generated by Django 5.2 on 2025-04-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100)),
                ('prompt', models.CharField(max_length=100)),
                ('answer', models.CharField(max_length=50)),
                ('choices', models.TextField()),
            ],
        ),
    ]
