# Generated by Django 5.2 on 2025-04-10 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(default='{"1": "Choice 1", "2": "Choice 2", "3": "Choice 3", "4": "Choice 4"}'),
        ),
    ]
