# Generated by Django 5.2 on 2025-04-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_alter_question_answer_alter_question_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='choices',
            field=models.TextField(default={'1': 'Choice 1', '2': 'Choice 2', '3': 'Choice 3', '4': 'Choice 4'}),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.CharField(default='Default Prompt', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='Default Question', max_length=100),
        ),
    ]
