# Generated by Django 5.2 on 2025-04-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(default='Default Question', max_length=100),
        ),
    ]
